### PR TITLE
Update to latest v2 addon tooling (v1.5.0)

### PR DESCRIPTION
**Pull request by SergeAstapov**
This is follow up to #384 but updates all `@embroider/*` packages to v1.1.0

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@ef4 would you mind to approve CI?

**Comment by ef4** [comment]
Done

**Comment by SergeAstapov** [comment]
@ef4 fixed setup (missed same dependency in /test-app), tests should be green now per [fork CI](https://github.com/SergeAstapov/ember-welcome-page/pull/1/checks)

**Comment by SergeAstapov** [comment]
@ef4 do you mind to land this so new apps use v1 of all `@embroider/*` packages by default so no pre-v1 hanging around?

**Pull request merged**
