### PR TITLE
Responsify welcome page #23

### PR DESCRIPTION
**Pull request by ryanlabouve**
I took a few liberties to responsify this. If there were project contraints that I have mistakenly overstepped, I'm happy to redo any of this.

I tried add as little code as possible to keep things small, but I did add two things of note:
* I did add a very small clearfix to get the floats to properly clear
* I added Paul Irish's infamous { box-sizing: border-box } to make the sizes easier to work with (http://www.paulirish.com/2012/box-sizing-border-box-ftw/)

Here's a GIF to demonstrate how the design resizes on a browser:
tomster-sizing

And here's a sanity check GIF from an actual phone to confirm all the viewport stuff is working as intended :
tomster-sizing-phone
(and by actual phone I totally mean the iPhone simulator 😉 )

Tomster appears visually off center due to him being positioned to the left in the image, while the sign pokes out to the right. Again, the element is centered, but Tomster _appears_ visually off-center. If this is an issue to anyone else I can fix here or in a separate issue.

### CODE REVIEW

**Comment by ryanlabouve** [comment]
Ooops! I forgot to link with this issue https://github.com/ember-cli/ember-welcome-page/issues/23

**Comment by locks** [comment]
> Again, the element is centered, but Tomster appears visually off-center. If this is an issue to anyone else I can fix here or in a separate issue.

Now I can't unsee it. Can you make a gif with Tomster centered at his torso instead?

**Comment by acorncom** [comment]
It's definitely more noticeable that Tomster's not centered when the whole setup is centered ;-)  It'd be nice to get that fixed, but I'd also argue that no one is actually going to see that on mobile (as you'd almost always wait to hook up a mobile phone to an Ember app until you'd made further progress).  So not sure it's a huge issue here either way ... ;-)

**Comment by locks** [comment]
@acorncom type `192.168.2.x` in your phone, boom ;P

**Comment by acorncom** [comment]
I stand corrected ;-)

**Comment by ryanlabouve** [comment]
I HAVE CRACKED THE CODE!

code-cracked

Optically centered Tomster via method in https://medium.com/@erqiudao/the-play-button-is-not-optical-alignment-4cea11bda175#.3d5vcp92x

Now on narrow screens:

welcome_to_ember_

**Comment by rwjblue** [comment]
LGTM, thank you!

**Pull request merged**
