### PR TITLE
Delegate template and styles build to ember-cli defaults

### PR DESCRIPTION
**Pull request by ro0gr**
Hi guys,

Today I've started getting `Welcome Page` for my new test app. Looks pretty nice. 

Anyway after digging into the `ember-welcome-page` sources I was curious if it possible to reduce complexity in the index.js  using `ember-cli` defaults as much as possible.

From the first perspective looks like this pr proofs that it's absolutely possible. I haven't updated tests at this point. 

Do you have any concerns about it?

### CODE REVIEW

**Comment by acorncom** [comment]
Hi there.  We actually specifically *didn't* do what you're suggesting to keep from having any impact on the consuming app's CSS / templates.  If you look back through the history of the add-on, you'll notice that my early prototypes did exactly what you're showing ;-)  As such, I think we'll close this for now.

Appreciate the feedback though (and if you notice any bugs, would love to get PRs for them!)

**Comment by rwjblue** [comment]
Ya, very specifically having this addon included (into any app) should **never** change the resulting build assets.

**Comment by ro0gr** [comment]
Now I see why it's done this way. And I'm glad about it :) 
Thank you.

**Comment by acorncom** [comment]
👍 ;-)

**Pull request closed without merging**
